# Generated by Django 4.2.9 on 2024-02-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audney", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="has_dependents",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("no", "No")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="income_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("55001_89000", "$55,001 - $89,000"),
                    ("89001_150000", "$89,001 - $150,000"),
                    ("150001_plus", "$150,001+"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="risk_tolerance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aggressive", "Aggressive"),
                    ("moderate", "Moderate"),
                    ("conservative", "Conservative"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="savings_months",
            field=models.CharField(
                blank=True,
                choices=[
                    ("3_months", "3 months"),
                    ("6_months", "6 months"),
                    ("9_months", "9 months"),
                    ("12_months", "12 months"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
