# Generated by Django 4.2.9 on 2024-02-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audney", "0002_userprofile_has_dependents_userprofile_income_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="from_stock_check",
            field=models.BooleanField(default=False),
        ),
    ]
