# Generated by Django 4.2.9 on 2024-02-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audney", "0004_audneymessage_stockpriceresponse_usermessage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audneymessage",
            name="user_query",
            field=models.TextField(blank=True, null=True),
        ),
    ]
