# Generated by Django 4.2.9 on 2024-02-19 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audney", "0005_audneymessage_user_query"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockpriceresponse",
            old_name="response",
            new_name="ticker_quote",
        ),
    ]
