# Generated by Django 4.2.9 on 2024-09-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audney", "0006_rename_response_stockpriceresponse_ticker_quote"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="experience_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
