# Generated by Django 4.2.9 on 2024-10-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audney", "0008_userprofile_city_userprofile_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="income_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("<55000", "<$55,000"),
                    ("55001_89000", "$55,001 - $89,000"),
                    ("89001_150000", "$89,001 - $150,000"),
                    ("150001_plus", "$150,001+"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="savings_months",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0_months", "0 months"),
                    ("3_months", "3 months"),
                    ("6_months", "6 months"),
                    ("9_months", "9 months"),
                    ("12_months", "12 months"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
